version: '3.3'
services:
  frontend:
    image: dnevskiy/foodgram_frontend:v1.0
    volumes:
      - ../frontend/:/app/result_build/
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres:/var/lib/postgres/data/
    env_file:
      - ./.env
  backend:
    image: dnevskiy/foodgram_backend:v1.0
    restart: always
    volumes:
      - static_value:/app/back_static/
      - media_value:/app/back_media/
      - docs:/app/api/docs/
    depends_on:
      - db
    env_file:
      - ./.env

  nginx:
    image: nginx:1.21.3-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - docs:/usr/share/nginx/html/api/docs/
      - static_value:/var/html/back_static/
      - media_value:/var/html/back_media/
    depends_on:
      - backend


volumes:
  static_value:
  media_value:
  postgres:
  docs: